services:
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    volumes:
      - ollama_models:/root/.ollama

  spectra-api:
    build: .
    depends_on:
      - ollama
    environment:
      HOST: 0.0.0.0
      PORT: 8000
      ENVIRONMENT: production
      SPECTRA_LOG_FORMAT: json
      SPECTRA_LOG_LEVEL: INFO
      ALLOWED_ORIGINS: http://localhost:3000,http://127.0.0.1:3000
      OLLAMA_MODEL: openhermes:7b-mistral-v2.5-q4_K_M
      OLLAMA_HOST: http://ollama:11434
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: nginx:stable-alpine
    depends_on:
      - spectra-api
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
    environment:
      - NGINX_PORT=80
    ports:
      - "3000:80"
    restart: unless-stopped

volumes:
  ollama_models:
