name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install backend deps
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run backend tests
        run: pytest -q --junitxml=tests/results.xml

      - name: Upload pytest report on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: tests/results.xml

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: frontend/package.json

      - name: Install frontend deps
        working-directory: frontend
        run: npm ci || npm install

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Archive production build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist
          retention-days: 7 