name: Spectra AI Backend Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Update to latest stable

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.in
          pip install pytest

      - name: Run pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q --junitxml=tests/results.xml  # Ensure report generation

      - name: Upload pytest report on failure
        if: failure()
        uses: actions/upload-artifact@v4  # Update to v4
        with:
          name: pytest-results
          path: tests/results.xml 